import numpy as np
import pandas as pd
import librosa as lb
import matplotlib.pyplot as plt
import scipy
# load audio sample, None keeps the original sample rate, 22.5kHz was chosen in this case for less computational burden.
data, sample_rate = lb.load("data/01 - Divinity.flac", sr=11250, duration=1.0) # 30s clip, 5s in
sample = lb.display.waveshow(data, sr=sample_rate)

## creation of mcmc using Metropolis-Hastings
# here I will be using a Laplace distribution, as that seems to be the general consensus when it comes to sparse data. 
# all credit for most of the code goes to https://github.com/Joseph94m/MCMC/blob/master/MCMC.ipynb
# create the proposal_distribution that determines the parameter step sizes that our parameters will explore within the parameter space.
proposal_distribution = lambda theta: [np.random.normal(theta[0],0.1), # new mu proposal
                                       np.random.normal(theta[1],0.05)] # slightly less for b since b is sensitive in laplacian
# the prior forms prior assumptions that help with the uncertainty that we have about our parameter space.
def log_prior(theta):
    mu, b = theta[0], theta[1]
    if b <= 0:
        return -np.inf  # hard constraint, log(0) = -inf
    log_prior_mu = scipy.stats.norm(0, 1).logpdf(mu)
    log_prior_b = scipy.stats.halfnorm(0, 1).logpdf(b)
    return log_prior_mu + log_prior_b
# using prior distribution assuming data is generated by a laplacian, the log-likelihood function is given by
def laplace_log_likelihood(theta, data):
    mu, b = theta[0], theta[1]
    if b <= 0:
        return -np.inf
    n = len(data)
    return -n * np.log(2 * b) - (1 / b) * np.sum(np.abs(data - mu))
def log_posterior(theta, data):
    return laplace_log_likelihood(theta, data) + log_prior(theta)
def acceptance(theta, theta_new):
    if theta_new > theta:
        return True
    else:
        accept = np.random.uniform(0, 1)
        return (np.log(accept) < (theta_new - theta))  # staying in log space throughout
def metropolis_hastings(data, initial_params, n_samples):
    theta_current = initial_params
    samples = [theta_current]
    accepted = 0
    for _ in range(n_samples):
        theta_new = proposal_distribution(theta_current)
        # evaluate log posteriors
        current_log_post = log_posterior(theta_current, data)
        new_log_post = log_posterior(theta_new, data)
        # accept or reject
        if acceptance(current_log_post, new_log_post):
            theta_current = theta_new
            accepted += 1
        samples.append(theta_current)
    print(f"Acceptance rate: {accepted / n_samples:.2%}")
    return np.array(samples)
#samples = metropolis_hastings(
#    data=data,
#    initial_params=[0.0, 1.0],  # initial guess for [mu, b]
#    n_samples=10000
#)

#mu_samples = samples[:, 0]
#b_samples = samples[:, 1]
#print(f"Estimated mu: {mu_samples.mean():.4f} ± {mu_samples.std():.4f}")
#print(f"Estimated b:  {b_samples.mean():.4f} ± {b_samples.std():.4f}\n")

# if librosa waveshow provides object adaptive.waveplot, and that provides y (audio time series), and times,
# should be able to assign time values separate and use them for both plots' x-axes.
#original_waveplot = lb.display.waveshow(data, sr=sample_rate)
#waveplot_times = original_waveplot.times
#original_waveplot_samples = original_waveplot.samples
#pred_laplace = scipy.stats.laplace.pdf(waveplot_times,mu_samples.mean(), b_samples.mean())
#print(original_waveplot_samples.shape)

#print(sampled_waveplot.shape)
# figure our plotting issues.
# Create the plot
#plt.figure(figsize=(10, 4))
#plt.plot(original_waveplot_samples, waveplot_times)
#plt.plot(pred_laplace, waveplot_times)
#plt.title('Waveform')
#plt.xlabel('Time (s)')
#plt.ylabel('Amplitude')
#plt.show()
