import numpy as np
import librosa as lb
import matplotlib.pyplot as plt
import scipy
# load audio sample, None keeps the original sample rate, 22.5kHz was chosen in this case for less computational burden.
data, sample_rate = lb.load("/home/gnix/Music/Mort Garson - Mother Earth's Plantasia/Mort Garson - Mother Earth's Plantasia - 01-05 Concerto for Philodendron & Pothos.flac", sr=22500, duration=30, offset=5.0) # 30s clip, 5s in
## creation of mcmc using Metropolis-Hastings
# here I will be using a Laplace distribution, as that seems to be the general consensus when it comes to sparse data. 
# all credit for most of the code goes to https://github.com/Joseph94m/MCMC/blob/master/MCMC.ipynb
# create the proposal_distribution that determines the parameter step sizes that our parameters will explore within the parameter space.
proposal_distribution = lambda theta: [np.random.normal(theta[0],0.1), # new mu proposal
                                       np.random.normal(theta[1],0.05)] # slightly less for b since b is sensitive in laplacian
# the prior forms prior assumptions that help with the uncertainty that we have about our parameter space.
def log_prior(x):
    mu, b = x[0], x[1]
    if b <= 0:
        return -np.inf  # hard constraint, log(0) = -inf
    log_prior_mu = scipy.stats.norm(0, 1).logpdf(mu)
    log_prior_b = scipy.stats.halfnorm(0, 1).logpdf(b)
    return log_prior_mu + log_prior_b

# using prior distribution assuming data is generated by a laplacian, the log-likelihood function is given by
def laplace_log_likelihood(theta, data):
    mu, b = theta[0], theta[1]
    if b <= 0:
        return -np.inf
    n = len(data)
    return -n * np.log(2 * b) - (1 / b) * np.sum(np.abs(data - mu))

def log_posterior(x, data):
    return laplace_log_likelihood(x, data) + log_prior(x)

def acceptance(x, x_new):
    if x_new > x:
        return True
    else:
        accept = np.random.uniform(0, 1)
        return (np.log(accept) < (x_new - x))  # staying in log space throughout

def metropolis_hastings(data, initial_params, n_samples):
    x_current = initial_params
    samples = [x_current]
    accepted = 0

    for i in range(n_samples):
        x_new = proposal_distribution(x_current)

        # evaluate log posteriors
        current_log_post = log_posterior(x_current, data)
        new_log_post = log_posterior(x_new, data)

        # accept or reject
        if acceptance(current_log_post, new_log_post):
            x_current = x_new
            accepted += 1

        samples.append(x_current)

    print(f"Acceptance rate: {accepted / n_samples:.2%}")
    return np.array(samples)

samples = metropolis_hastings(
    data=data,
    initial_params=[0.0, 1.0],  # initial guess for [mu, b]
    n_samples=10000
)

mu_samples = samples[:, 0]
b_samples = samples[:, 1]

print(f"Estimated mu: {mu_samples.mean():.4f} ± {mu_samples.std():.4f}")
print(f"Estimated b:  {b_samples.mean():.4f} ± {b_samples.std():.4f}")

# figure our plotting issues.
# Create the plot
#plt.figure(figsize=(10, 4))
#lb.display.waveshow(data, sr=sample_rate)
#lb.display.waveshow(samples,sr=sample_rate)
#plt.title('Waveform')
#plt.xlabel('Time (s)')
#plt.ylabel('Amplitude')
#plt.show()
